### PR TITLE
redesign signin page

### PR DESCRIPTION
**Pull request by PalmerAL**
@nt1m Any suggestions? (particularly with the descriptions and anything else you think needs to be added)

I plan to add the scratchpad name + logo at the top once #102 is fixed.

### CODE REVIEW

**Comment by nt1m** [comment]
So content-wise, the only thing I miss is a full screenshot (leaving the add menu open in the screenshot is a good idea as well). To be honest, the first thing I try to find before I even download or sign up is a screenshot. That screenshot could possibly be annotated kinda like on the chrome first run page.

Design-wise, the black and white design is pretty gloomy and not in the spirit of Material Design. MD is supposed to be colorful and delightful :) You could try adding a wallpaper as background  Adding the logo probably won't change the situation much. 
The big animated headline with auto replaing text is a pretty neat idea ! Although, instead of highlighting green the word that is about to be deleted, I would pretend the user is using backspace .

**Comment by PalmerAL** [comment]
> So content-wise, the only thing I miss is a full screenshot (leaving the add menu open in the screenshot is a good idea as well). To be honest, the first thing I try to find before I even download or sign up is a screenshot. That screenshot could possibly be annotated kinda like on the chrome first run page.

Fixed. I thought about an annoted screenshot, but it won't work on mobile.

**Comment by PalmerAL** [comment]
> Design-wise, the black and white design is pretty gloomy and not in the spirit of Material Design. MD is supposed to be colorful and delightful :) You could try adding a wallpaper as background Adding the logo probably won't change the situation much. 

Adding a wallpaper takes away from the text and buttons, which is what the focus should be on. I think that changing the feature-block headings to teal helps with this?

It might also be good to change the background of the hero at the bottom to a color other than black. The blue button doesn't look good on teal unfortunately, and the pink doesn't look right, so I'm not sure how to solve this one.

**Comment by nt1m** [comment]
@PalmerAL I really don't see how a wallpaper takes away the attention : https://www.google.com/docs/about/
If you really don't want a wallpaper, you could add an illustration : http://www.materialup.com/posts/find-your-next-home

About the colored headings, I haven't seen any in Material design yet, really depends on the rest of the design.

**Comment by PalmerAL** [comment]
Any suggestions on good wallpapers to use (that have a usable license)? It might look better with a wallpaper, but I'm having a hard time finding something that goes well with the text.

**Comment by nt1m** [comment]
Wallheaven has a nice collection of wallpapers, I think that site provides licensing info too.
Greg Ives on G+ also has a nice collection of walls (that don't belong to him though, but you can easily find the original license by doing a reverse image search) : 
- https://plus.google.com/photos/+GregIvesgrives/albums/6093919503863203009
- https://plus.google.com/photos/+GregIvesgrives/albums/6029705621078575281

**Comment by PalmerAL** [comment]
https://unsplash.com/photos/t7YycgAoVSw/download maybe?
(although the spec does say not to use metaphorical imagery)

Greg Ives' photos are hard to find licensing info on, most appear on other sites but with no licensing information.

**Comment by nt1m** [comment]
@PalmerAL That photo looks OK. FYI, you don't have to do everything like MD.

**Comment by PalmerAL** [comment]
Anything else before this is merged?

**Comment by nt1m** [comment]
I would just remove the horizontal scrolling, but otherwise, it looks good.

**Comment by PalmerAL** [comment]
Done.

**Pull request merged**
